closeall;
clear;

theta = linspace(40,56,10000);                    # angle vector
lambda=570e-9;

n_AlO=1.65+1i*1e-4;
n_in=1.5;
n_out=1;
nL=1.49+1i*1e-4;
nH=2.53+1i*1e-4;
ntail=1.49;

loaddata('best_param');
parameters = best_parameters;
tail = parameters(1);
dlastTitania = parameters(2);
dAlO = parameters(3);
dsecondlastTitania = 0; # parameters(4);
dlastSilica = parameters(5);
dL = parameters(6);
dH = parameters(7);

N=11;



# N high-low couples + one for substrate, one for air, one for the pmma layer, one for last titania
# one for allumina protective layer and one for second last titania.
N_layers=2*N+6;    

n1 = matrix(N_layers);
d  = matrix(N_layers);
n_effective = matrix(3);
n1(1) = n_in;
n1(2:2:2*N) = nH;
n1(3:2:2*N+1) = nL;
n1(end-4) = nH;#;
n1(end-3) = n_AlO;
n1(end-2) = nH;
n1(end-1) = ntail;
n1(end) = n_out;
for (i=1:3){
    if(i==2){ tail = 0; n_eff2 = sin(theta(idx)*pi/180)*n_in;}
    if(i==3){ dlastTitania = 0; n_eff3 = sin(theta(idx)*pi/180)*n_in;}
    
    d(1) = 1e-6;
    d(2:2:2*N) = dH;
    d(3:2:2*N+1) = dL;
    d(end-5) = dlastSilica;
    d(end-4) = dsecondlastTitania;
    d(end-3) = dAlO;
    d(end-2) = dlastTitania;
    d(end-1) = tail;
    d(end) = 5e6;
    
    RT1 = stackrt(n1,d,c/lambda,theta);
    
    #image(RT1.theta,RT1.lambda*1e6,transpose(RT1.Rp),"theta (deg)","wavelength (um)","Rp, dispersive example");    
    
    idx=findpeaks(1-RT1.Rp);
    field = stackfield(n1,d,c/lambda,theta(idx),1e4,0,5e-6);
    H=abs(pinch(sqrt(field.Hp(1,1,:,1,1,1)^2+field.Hp(1,1,:,1,1,2)^2+field.Hp(1,1,:,1,1,3)^2)))^2;#
    z=field.z;
    
    if (i==1) { 
        n_eff1 = sin(theta(idx)*pi/180)*n_in;
        idx_layers = n1;
        d_layers = d;
        nz = n1(1)*ones(length(z));
        for (i=1:length(z)) {
            for (j=2:length(d)) {
                if ((z(i)<=sum(d(1:j))&(z(i)>sum(d(1:j-1))))) {
                    nz(i)=n1(j);
                }
            }
        }
        plot(theta,RT1.Rp); 
        plot(z,H);
    } else {
        selectfigure(1);
        holdon;
        plot(theta,RT1.Rp); 
        selectfigure(2);
        holdon;
        plot(z,H);
    }    
}

selectfigure(2);
holdon;
plot(z,real(nz)*200);


savedata('best_design',idx_layers,d_layers,n_eff1,n_eff2,n_eff3);
