closeall;
clear;

theta = linspace(40,56,10000);                    # angle vector
lambda=570e-9;

n_Ti2O2=2.53+1i*1e-4;                          # high refractive index
n_AlO=1.65+1i*1e-4;                            # low refractive index
n_SiO2=1.46;                                   # low refractive index
n_pmma=1.48+1i*1e-4;
n_Ta2O5=2.08+1i*1e-4;                          # high refractive inde

# the stack is fixed to be S-(B-A)xN-B-AlO-last-tail-air
scale_period = 1.03;
loaddata('best_param'+'3');#num2str(kkk)
parameters = best_parameters;
indeces = best_index;
tail = parameters(1);
dlast = 60e-9-10e-9;# parameters(2)*0.85;
dAlO = 25e-9;parameters(3);
dsecondlast_B = 57e-9;#parameters(4)*scale_period;
dsecondlast_A = 133e-9;#parameters(5)*scale_period;
dA = 133e-9;#parameters(6)*scale_period;
dB = 57e-9;#parameters(7)*scale_period;

n_in = indeces(1);        
n_out = indeces(2);       
nA = indeces(3);          
nB = indeces(4);          
nlast = indeces(5);      
ntail = indeces(6);       

N = parameters(8)+3;    

# the stack is fixed to be S-(B-A)xN-B-AlO-last-tail-air

# N high-low couples + one for substrate, one for air, one for the pmma layer, one for last titania
# one for allumina protective layer and one for second last titania.
N_layers=2*N+6;    

n1 = matrix(N_layers);
d  = matrix(N_layers);
n_effective = matrix(3);
n1(1) = n_in;
n1(2:2:2*N) = nB;
n1(3:2:2*N+1) = nA;
n1(end-4) = nB;
n1(end-3) = n_AlO;
n1(end-2) = nlast;
n1(end-1) = ntail;
n1(end) = n_out;
for (i=[1:3]){
    if(i==2){ tail = 0; }
    if(i==3){ dlast = 0;}
    
    d(1) = 1e-6;
    d(2:2:2*N) = dB;
    d(3:2:2*N+1) = dA;
    d(end-5) = dsecondlast_A;
    d(end-4) = dsecondlast_B;
    d(end-3) = dAlO;
    d(end-2) = dlast;
    d(end-1) = tail;
    d(end) = 5e6;
    
    RT1 = stackrt(n1,d,c/lambda,theta);
    
    #image(RT1.theta,RT1.lambda*1e6,transpose(RT1.Rp),"theta (deg)","wavelength (um)","Rp, dispersive example");    
    
    idx=findpeaks(1-RT1.Rp);
    field = stackfield(n1,d,c/lambda,theta(idx),1e4,0,7e-6);
    H=abs(pinch(sqrt(field.Hp(1,1,:,1,1,1)^2+field.Hp(1,1,:,1,1,2)^2+field.Hp(1,1,:,1,1,3)^2)))^2;#
    z=field.z;
    
    if (i==1) { 
        n_eff1 = sin(theta(idx)*pi/180)*n_in;
        idx_layers = n1;
        ?d_layers = d;
        nz = n1(1)*ones(length(z));
        for (i=1:length(z)) {
            for (j=2:length(d)) {
                if ((z(i)<=sum(d(1:j))&(z(i)>sum(d(1:j-1))))) {
                    nz(i)=n1(j);
                }
            }
        }
        plot(theta,RT1.Rp,RT1.Tp); 
        selectfigure(2);
        plot(z,H);
    } else {
        if(i==2){ n_eff2 = sin(theta(idx)*pi/180)*n_in; }
        else {    n_eff3 = sin(theta(idx)*pi/180)*n_in; 
        selectfigure(1);
        holdon;
        plot(theta,RT1.Rp); 
        selectfigure(2);
        holdon;
        plot(z,H);
        }
    }    
}
?n_eff1/n_eff3;
selectfigure(2);
holdon;
plot(z,real(nz)*400);
legend('Field with last layer', 'Field without last layer', 'Refreactive index x 400');
selectfigure(1);
legend('With last layer', 'Without last layer');
        
N_l=length(d_layers);
for (i=2;i<N_l;i=i+1){
    N_l=length(d_layers);
    if (d_layers(i)==0){
        d_new=matrix(N_l-1);
        idx_new=matrix(N_l-1);
        
        d_new(1:i-1)  =d_layers(1:i-1);
        d_new(i:N_l-1)=d_layers(i+1:N_l);
        idx_new(1:i-1)  =idx_layers(1:i-1);
        idx_new(i:N_l-1)=idx_layers(i+1:N_l);
        
        idx_layers=idx_new;
        d_layers  =d_new;
        i=1;
    } 
}        

savedata('designs/best_design_TM5',idx_layers,d_layers,n_eff1,n_eff2,n_eff3);
